#!/usr/bin/env python3
"""
AgentForge Remédiation Stratégique - Body PDF Generator
ReportLab pipeline - generates body PDF (no cover)
"""

import hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm, mm
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, CondPageBreak, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('LiberationSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Italic', '/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf'))
pdfmetrics.registerFont(TTFont('Carlito', '/usr/share/fonts/truetype/english/Carlito-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Carlito-Bold', '/usr/share/fonts/truetype/english/Carlito-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC', '/usr/share/fonts/truetype/chinese/SarasaMonoSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC-Bold', '/usr/share/fonts/truetype/chinese/SarasaMonoSC-Bold.ttf'))

registerFontFamily('LiberationSerif', normal='LiberationSerif', bold='LiberationSerif-Bold', italic='LiberationSerif-Italic')
registerFontFamily('Carlito', normal='Carlito', bold='Carlito-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')
registerFontFamily('SarasaMonoSC', normal='SarasaMonoSC', bold='SarasaMonoSC-Bold')

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
ACCENT       = colors.HexColor('#5132b0')
TEXT_PRIMARY  = colors.HexColor('#22211e')
TEXT_MUTED    = colors.HexColor('#7f7c73')
BG_SURFACE   = colors.HexColor('#e3e1db')
BG_PAGE      = colors.HexColor('#f5f4f2')

TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# Priority colors
COLOR_CRITIQUE = colors.HexColor('#c0392b')
COLOR_HAUTE    = colors.HexColor('#d35400')
COLOR_MOYENNE  = colors.HexColor('#2c7a4a')
COLOR_FAIBLE   = colors.HexColor('#7f8c8d')
COLOR_VALIDE   = colors.HexColor('#1a7a3a')

# ━━ Page Setup ━━
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 0.8 * inch
RIGHT_MARGIN = 0.8 * inch
TOP_MARGIN = 0.75 * inch
BOTTOM_MARGIN = 0.75 * inch
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ━━ Styles ━━
styles = getSampleStyleSheet()

# French body style (left-aligned, not justified since mixed French/symbols)
body_style = ParagraphStyle(
    'FrenchBody', parent=styles['Normal'],
    fontName='LiberationSerif', fontSize=10, leading=15,
    alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceBefore=0, spaceAfter=6
)

body_justified = ParagraphStyle(
    'FrenchBodyJustified', parent=body_style,
    alignment=TA_JUSTIFY
)

# Heading styles
h1_style = ParagraphStyle(
    'FrenchH1', parent=styles['Heading1'],
    fontName='LiberationSerif', fontSize=18, leading=24,
    alignment=TA_LEFT, textColor=ACCENT,
    spaceBefore=18, spaceAfter=10
)

h2_style = ParagraphStyle(
    'FrenchH2', parent=styles['Heading2'],
    fontName='LiberationSerif', fontSize=14, leading=19,
    alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceBefore=14, spaceAfter=8
)

h3_style = ParagraphStyle(
    'FrenchH3', parent=styles['Heading3'],
    fontName='LiberationSerif', fontSize=12, leading=16,
    alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceBefore=10, spaceAfter=6
)

# Table styles
table_header_style = ParagraphStyle(
    'TableHeader', fontName='LiberationSerif', fontSize=8,
    leading=10, alignment=TA_CENTER, textColor=TABLE_HEADER_TEXT,
    wordWrap='CJK'
)

table_cell_style = ParagraphStyle(
    'TableCell', fontName='LiberationSerif', fontSize=7.5,
    leading=10, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    wordWrap='CJK'
)

table_cell_center = ParagraphStyle(
    'TableCellCenter', fontName='LiberationSerif', fontSize=7.5,
    leading=10, alignment=TA_CENTER, textColor=TEXT_PRIMARY,
    wordWrap='CJK'
)

# Caption style
caption_style = ParagraphStyle(
    'Caption', fontName='LiberationSerif', fontSize=9,
    leading=12, alignment=TA_CENTER, textColor=TEXT_MUTED,
    spaceBefore=3, spaceAfter=6
)

# TOC styles
toc_h1_style = ParagraphStyle(
    'TOCH1', fontName='LiberationSerif', fontSize=13, leading=20,
    leftIndent=20, textColor=TEXT_PRIMARY
)
toc_h2_style = ParagraphStyle(
    'TOCH2', fontName='LiberationSerif', fontSize=11, leading=16,
    leftIndent=40, textColor=TEXT_MUTED
)

# Bullet style
bullet_style = ParagraphStyle(
    'BulletStyle', parent=body_style,
    leftIndent=20, bulletIndent=10,
    spaceBefore=2, spaceAfter=2
)

# Callout box style
callout_style = ParagraphStyle(
    'Callout', fontName='LiberationSerif', fontSize=10,
    leading=14, alignment=TA_LEFT, textColor=ACCENT,
    leftIndent=12, borderPadding=6,
    spaceBefore=6, spaceAfter=6
)

# ━━ TOC DocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def make_priority_cell(priority_text):
    """Return a Paragraph with colored text based on priority."""
    color_map = {
        'Critique': COLOR_CRITIQUE,
        'Haute': COLOR_HAUTE,
        'Moyenne': COLOR_MOYENNE,
        'Faible': COLOR_FAIBLE,
        'Valide': COLOR_VALIDE,
    }
    c = color_map.get(priority_text, TEXT_PRIMARY)
    hex_c = '#%02x%02x%02x' % (int(c.red*255), int(c.green*255), int(c.blue*255))
    return Paragraph('<b><font color="%s">%s</font></b>' % (hex_c, priority_text), table_cell_center)


def make_gap_cell(gap_text):
    """Return a Paragraph with colored gap percentage."""
    gap_val = int(gap_text.replace('%', ''))
    if gap_val >= 90:
        c = COLOR_CRITIQUE
    elif gap_val >= 70:
        c = COLOR_HAUTE
    elif gap_val >= 40:
        c = COLOR_MOYENNE
    elif gap_val > 0:
        c = colors.HexColor('#2980b9')
    else:
        c = COLOR_VALIDE
    hex_c = '#%02x%02x%02x' % (int(c.red*255), int(c.green*255), int(c.blue*255))
    return Paragraph('<b><font color="%s">%s</font></b>' % (hex_c, gap_text), table_cell_center)


def build_conformity_table():
    """Build the Phase 1 conformity matrix table."""
    data = [
        # (Exigence, Etat Actuel, Etat Cible, Priorite, Gap%)
        # MoA Orchestration
        ("1. 9 modeles paralleles en Propose", "Variable (3-7 par agent)", "9 paralleles", "Critique", "55%"),
        ("2. Critique croise multi-LLM", "Top 2 LLMs", "Tous avec voting", "Critique", "50%"),
        ("3. Refinement avec feedback integre", "Top 3 LLMs", "Tous avec feedback", "Haute", "40%"),
        ("4. Voting multicritere pondere", "Selection par score combine", "Weighted vote multicriteria", "Haute", "60%"),
        ("5. Early exit sur consensus", "Implemente (>=2 proposals >=0.85)", "Implemente", "Valide", "0%"),
        # Reflection Agent
        ("6. Evaluation LLM reelle", "Gemini 2.0 Flash", "Implemente", "Valide", "0%"),
        ("7. 6 criteres ponderes", "6 criteres (DEV)", "Implemente", "Valide", "0%"),
        ("8. Seuil 0.95 configurable", "0.95 DEV, 0.88-0.92 autres", "Implemente", "Valide", "0%"),
        ("9. Feedback loop vers MoA", "Feedback pour autofix", "Feedback injecte dans MoA", "Haute", "50%"),
        ("10. Historique d'evolution", "Non persiste", "Persistance DB", "Haute", "70%"),
        # RL Router
        ("11. Exploration epsilon-greedy", "Heuristique statique", "e-greedy avec decay", "Critique", "90%"),
        ("12. Reward engine", "Pas de reward", "Reward = f(quality, cost, latency)", "Critique", "95%"),
        ("13. Persistence en DB", "In-memory only", "rl_training_data persistee", "Critique", "85%"),
        ("14. Feedback utilisateur", "Non capture", "Thumbs up/down + rating", "Haute", "90%"),
        ("15. Dashboard de performance", "Non existant", "Metriques temps reel", "Haute", "95%"),
        # Cost Optimizer
        ("16. Scoring qualite/cout/latence", "50/30/20", "Configurable", "Valide", "10%"),
        ("17. Historique avec EMA", "EMA 10 dernieres", "Persistance + EMA glissant", "Haute", "40%"),
        ("18. Predictions de cout", "Estimation basique", "ML-based prediction", "Moyenne", "70%"),
        ("19. Apprentissage continu", "Pas de learning loop", "Auto-adjust weights", "Haute", "80%"),
        ("20. Budget tiers", "Selection budget-aware", "+ alerts", "Valide", "20%"),
        # Auto-Fix Enterprise
        ("21. Pattern library (200+)", "6 patterns", "200+ patterns", "Critique", "97%"),
        ("22. ts-morph / TS Compiler API", "Regex-based AST", "Vraie AST (ts-morph)", "Critique", "95%"),
        ("23. Type incompatibility detection", "Non detecte", "TypeScript type checking", "Haute", "95%"),
        ("24. Missing imports detection", "Basique (require->import)", "Full import resolution", "Haute", "80%"),
        ("25. Circular references", "Non detecte", "Dependency graph analysis", "Moyenne", "90%"),
        ("26. Dead code detection", "Non detecte", "AST traversal", "Moyenne", "95%"),
        ("27. Multi-pass LLM repair", "Single LLM call", "Multi-pass with context", "Haute", "70%"),
        # Context Management
        ("28. ContextGraph", "Non existant", "Full dependency graph", "Critique", "100%"),
        ("29. DependencyResolver", "Non existant", "Direct deps only", "Critique", "100%"),
        ("30. TokenBudgetManager", "Non existant", "Per-file token limits", "Critique", "100%"),
        ("31. ContextCompressionService", "Non existant", "Intelligent compression", "Haute", "100%"),
        ("32. Resume automatique", "Non existant", "Auto-summarize large contexts", "Haute", "100%"),
        # Sandbox Cloud Native
        ("33. Warm Pool Manager", "Pas de warm pool", "Pre-warmed containers", "Critique", "100%"),
        ("34. Demarrage <500ms", "~2-5s Docker cold start", "<500ms warm", "Critique", "90%"),
        ("35. SandboxScheduler", "Pas de scheduler", "Priority queue + scheduling", "Haute", "100%"),
        ("36. Auto-recovery", "Pas de recovery", "Auto-restart on failure", "Haute", "100%"),
        ("37. SandboxMetrics", "Pas de metriques", "CPU/memory/latency tracking", "Haute", "100%"),
        # Deploiement Automatise
        ("38. Cloudflare Pages/Workers", "Variables d'env seulement", "Full deployment engine", "Critique", "95%"),
        ("39. D1/KV/R2 support", "Non implante", "Full Cloudflare stack", "Haute", "100%"),
        ("40. Rollback capability", "Non implante", "Auto-rollback on failure", "Haute", "100%"),
        ("41. Preview deployments", "Non implante", "Branch-based previews", "Moyenne", "100%"),
        ("42. Blue/green + canary", "Non implante", "Progressive rollout", "Haute", "100%"),
        # Observabilite
        ("43. OpenTelemetry tracing", "Console.log", "OTEL distributed tracing", "Critique", "95%"),
        ("44. Metrics Service", "Health endpoint basique", "Prometheus-compatible", "Haute", "90%"),
        ("45. Alert Manager", "Non existant", "Threshold-based alerts", "Haute", "100%"),
        ("46. Real-time dashboard", "Non existant", "Grafana-style monitoring", "Haute", "100%"),
        # Admin Control Center
        ("47. Gestion utilisateurs", "CRUD basique auth routes", "Full admin CRUD + quotas", "Haute", "70%"),
        ("48. Gestion agents", "Static registry", "Dynamic config + activation", "Haute", "80%"),
        ("49. Gestion providers", "Pas d'admin", "Cost/quality/latency monitoring", "Haute", "95%"),
        ("50. Orchestration monitor", "SSE events", "DAG/MoA/Reflection monitor UI", "Haute", "80%"),
        ("51. Finance dashboard", "Pas de tracking", "Cost/revenue/margin", "Haute", "95%"),
        ("52. Securite admin", "Pas d'audit", "Audit logs + anomaly detection", "Haute", "95%"),
        ("53. Infrastructure monitor", "Health basique", "Cache/sandbox/queue/workers", "Haute", "90%"),
        # Securite Enterprise
        ("54. MFA TOTP", "JWT only", "TOTP-based MFA", "Critique", "100%"),
        ("55. Device Trust", "Non implante", "Device fingerprinting", "Haute", "100%"),
        ("56. Session Management", "JWT stateless", "Server-side sessions", "Haute", "90%"),
        ("57. Secret Rotation", "Manuel", "Auto-rotation", "Haute", "100%"),
        ("58. Security Dashboard", "Non existant", "Threat detection + audit", "Haute", "100%"),
        ("59. Audit Trail", "Non existant", "Full action logging", "Haute", "100%"),
        # Qualite Logicielle
        ("60. Tests unitaires", "0% coverage", ">80%", "Critique", "100%"),
        ("61. Tests integration", "0%", "API + service integration", "Critique", "100%"),
        ("62. Tests E2E", "0%", "Critical user flows", "Haute", "100%"),
        ("63. Load testing", "0%", "k6/Artillery benchmarks", "Moyenne", "100%"),
        ("64. Chaos testing", "0%", "Failure injection", "Faible", "100%"),
        # Multi-Tenant
        ("65. Tenant isolation", "Shared DB", "Schema-per-tenant ou row-level", "Critique", "100%"),
        ("66. Quotas par tenant", "Tier basique", "Fine-grained quotas", "Haute", "85%"),
        ("67. Facturation", "Non implante", "Stripe/billing integration", "Haute", "100%"),
        ("68. Branding", "Non implante", "Custom themes/logos", "Faible", "100%"),
        ("69. RBAC avance", "3 tiers", "Super Admin/Tenant Admin/Team Manager", "Haute", "80%"),
        # Performance
        ("70. Redis Cluster", "Single Redis", "Redis Cluster", "Haute", "90%"),
        ("71. Job Queue", "Direct execution", "BullMQ/job queue", "Critique", "100%"),
        ("72. Horizontal Scaling", "Single instance", "Stateless + LB", "Haute", "95%"),
        ("73. Cache distribue", "L1+L2 single node", "Distributed cache layer", "Haute", "80%"),
    ]

    # Build table data with Paragraph objects
    header = [
        Paragraph('<b>No.</b>', table_header_style),
        Paragraph('<b>Exigence Blueprint</b>', table_header_style),
        Paragraph('<b>Etat Actuel</b>', table_header_style),
        Paragraph('<b>Etat Cible</b>', table_header_style),
        Paragraph('<b>Priorite</b>', table_header_style),
        Paragraph('<b>Gap%</b>', table_header_style),
    ]

    table_data = [header]
    for row in data:
        num_end = row[0].index('.')
        num = row[0][:num_end]
        exigence = row[0][num_end+1:].strip()
        table_data.append([
            Paragraph(num, table_cell_center),
            Paragraph(exigence, table_cell_style),
            Paragraph(row[1], table_cell_style),
            Paragraph(row[2], table_cell_style),
            make_priority_cell(row[3]),
            make_gap_cell(row[4]),
        ])

    # Column widths: proportional to content
    col_widths = [
        0.04 * AVAILABLE_WIDTH,   # No.
        0.27 * AVAILABLE_WIDTH,   # Exigence
        0.23 * AVAILABLE_WIDTH,   # Etat Actuel
        0.23 * AVAILABLE_WIDTH,   # Etat Cible
        0.10 * AVAILABLE_WIDTH,   # Priorite
        0.08 * AVAILABLE_WIDTH,   # Gap%
    ]

    table = Table(table_data, colWidths=col_widths, hAlign='CENTER', repeatRows=1)

    # Build style commands
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.4, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]

    # Alternating row colors
    for i in range(1, len(table_data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))

    # Section separator lines for categories
    section_starts = [1, 6, 11, 16, 21, 28, 33, 38, 43, 47, 54, 60, 65, 70]
    for s in section_starts:
        if s < len(table_data):
            style_cmds.append(('LINEABOVE', (0, s), (-1, s), 1.2, ACCENT))

    table.setStyle(TableStyle(style_cmds))
    return table


def build_phase_table(phase_num, phase_title, rows):
    """Build a phase summary table with: Composant | Fichier | Description | Impact"""
    header = [
        Paragraph('<b>Composant</b>', table_header_style),
        Paragraph('<b>Fichier</b>', table_header_style),
        Paragraph('<b>Description</b>', table_header_style),
        Paragraph('<b>Impact</b>', table_header_style),
    ]
    table_data = [header]
    for row in rows:
        table_data.append([
            Paragraph(row[0], table_cell_style),
            Paragraph(row[1], table_cell_style),
            Paragraph(row[2], table_cell_style),
            Paragraph(row[3], table_cell_center),
        ])

    col_widths = [0.22, 0.30, 0.33, 0.12]
    col_widths = [r * AVAILABLE_WIDTH for r in col_widths]

    table = Table(table_data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.4, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]
    for i in range(1, len(table_data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    table.setStyle(TableStyle(style_cmds))
    return table


def build_risk_table():
    """Build the risk assessment table."""
    header = [
        Paragraph('<b>Risque</b>', table_header_style),
        Paragraph('<b>Probabilite</b>', table_header_style),
        Paragraph('<b>Impact</b>', table_header_style),
        Paragraph('<b>Mitigation</b>', table_header_style),
    ]

    risks = [
        ("Regression fonctionnelle", "Haute", "Critique", "Tests E2E avant chaque phase + rollback automatique"),
        ("Incompatibilite API Cloudflare", "Moyenne", "Haute", "Prototype sur environnement de staging en Phase 1"),
        ("Surcharge memoire (Warm Pool)", "Moyenne", "Haute", "Monitoring + auto-scaling + hard limits par container"),
        ("Divergence LLM providers", "Moyenne", "Moyenne", "Abstraction provider + fallback multi-provider"),
        ("Latence accrue (OTEL)", "Faible", "Moyenne", "Sampling rate configurable + async export"),
        ("Complexite multi-tenant", "Haute", "Critique", "Schema isolation progressive + validation Parquet"),
        ("Dettes techniques accumulees", "Haute", "Haute", "Refactoring incrementale + code review obligatoire"),
        ("Resistance organisationnelle", "Moyenne", "Moyenne", "Formation equipes + documentation exhaustive"),
    ]

    table_data = [header]
    for r in risks:
        table_data.append([
            Paragraph(r[0], table_cell_style),
            make_priority_cell(r[1]),
            make_priority_cell(r[2]),
            Paragraph(r[3], table_cell_style),
        ])

    col_widths = [0.22, 0.12, 0.12, 0.50]
    col_widths = [w * AVAILABLE_WIDTH for w in col_widths]

    table = Table(table_data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.4, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]
    for i in range(1, len(table_data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    table.setStyle(TableStyle(style_cmds))
    return table


def build_conformity_score_table():
    """Build the conformity score calculation table."""
    header = [
        Paragraph('<b>Domaine</b>', table_header_style),
        Paragraph('<b>Exigences</b>', table_header_style),
        Paragraph('<b>Validees</b>', table_header_style),
        Paragraph('<b>Score Actuel</b>', table_header_style),
        Paragraph('<b>Score Cible</b>', table_header_style),
        Paragraph('<b>Ecart</b>', table_header_style),
    ]

    domains = [
        ("MoA Orchestration", 5, 2, "46%", "100%", "54%"),
        ("Reflection Agent", 5, 3, "60%", "100%", "40%"),
        ("RL Router", 5, 0, "5%", "100%", "95%"),
        ("Cost Optimizer", 5, 2, "52%", "100%", "48%"),
        ("Auto-Fix Enterprise", 7, 0, "3%", "100%", "97%"),
        ("Context Management", 5, 0, "0%", "100%", "100%"),
        ("Sandbox Cloud Native", 5, 0, "0%", "100%", "100%"),
        ("Deploiement Automatise", 5, 0, "2%", "100%", "98%"),
        ("Observabilite", 4, 0, "3%", "100%", "97%"),
        ("Admin Control Center", 7, 0, "7%", "100%", "93%"),
        ("Securite Enterprise", 6, 0, "2%", "100%", "98%"),
        ("Qualite Logicielle", 5, 0, "0%", "100%", "100%"),
        ("Multi-Tenant", 5, 0, "3%", "100%", "97%"),
        ("Performance", 4, 0, "5%", "100%", "95%"),
    ]

    table_data = [header]
    for d in domains:
        table_data.append([
            Paragraph(d[0], table_cell_style),
            Paragraph(str(d[1]), table_cell_center),
            Paragraph(str(d[2]), table_cell_center),
            make_gap_cell(d[3]),
            Paragraph(d[4], table_cell_center),
            make_gap_cell(d[5]),
        ])

    # Total row
    total_exig = sum(d[1] for d in domains)
    total_val = sum(d[2] for d in domains)
    # Calculate weighted average
    current_scores = [int(d[3].replace('%','')) for d in domains]
    avg_current = sum(current_scores) / len(current_scores)

    table_data.append([
        Paragraph('<b>TOTAL</b>', table_cell_style),
        Paragraph('<b>%d</b>' % total_exig, table_cell_center),
        Paragraph('<b>%d</b>' % total_val, table_cell_center),
        Paragraph('<b>%.0f%%</b>' % avg_current, table_cell_center),
        Paragraph('<b>100%</b>', table_cell_center),
        Paragraph('<b>%.0f%%</b>' % (100 - avg_current), table_cell_center),
    ])

    col_widths = [0.28, 0.10, 0.10, 0.16, 0.16, 0.16]
    col_widths = [w * AVAILABLE_WIDTH for w in col_widths]

    table = Table(table_data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.4, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        # Bold total row
        ('BACKGROUND', (0, -1), (-1, -1), BG_SURFACE),
        ('LINEABOVE', (0, -1), (-1, -1), 1.5, ACCENT),
    ]
    for i in range(1, len(table_data) - 1):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    table.setStyle(TableStyle(style_cmds))
    return table


def build_file_list_table(rows, title):
    """Build a file list table with: Fichier | Type | Phase | Description"""
    header = [
        Paragraph('<b>Fichier</b>', table_header_style),
        Paragraph('<b>Type</b>', table_header_style),
        Paragraph('<b>Phase</b>', table_header_style),
        Paragraph('<b>Description</b>', table_header_style),
    ]
    table_data = [header]
    for r in rows:
        table_data.append([
            Paragraph(r[0], table_cell_style),
            Paragraph(r[1], table_cell_center),
            Paragraph(r[2], table_cell_center),
            Paragraph(r[3], table_cell_style),
        ])

    col_widths = [0.35, 0.10, 0.08, 0.43]
    col_widths = [w * AVAILABLE_WIDTH for w in col_widths]

    table = Table(table_data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.4, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]
    for i in range(1, len(table_data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    table.setStyle(TableStyle(style_cmds))
    return table


def build_document():
    """Main document builder."""
    output_path = '/home/z/my-project/download/body.pdf'

    doc = TocDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN,
        bottomMargin=BOTTOM_MARGIN,
        showBoundary=0
    )

    story = []
    H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

    # ━━━━━━━━━━━━ TABLE OF CONTENTS ━━━━━━━━━━━━
    story.append(Paragraph('<b>TABLE DES MATIERES</b>', h1_style))
    story.append(Spacer(1, 12))

    toc = TableOfContents()
    toc.levelStyles = [toc_h1_style, toc_h2_style]
    story.append(toc)
    story.append(PageBreak())

    # ━━━━━━━━━━━━ PHASE 1: CONFORMITY MATRIX ━━━━━━━━━━━━
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    story.append(add_heading('<b>PHASE 1 - MATRICE DE CONFORMITE</b>', h1_style, level=0))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "La matrice de conformite ci-dessous presente l'analyse detaillee de l'ensemble des 73 exigences "
        "du blueprint AgentForge, comparees a l'etat actuel de la plateforme MVP. Chaque exigence est "
        "evaluee selon son etat actuel, son etat cible, sa priorite de remédiation, et le pourcentage "
        "d'ecart (gap) restant a combler.",
        body_justified
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Les priorites sont classees comme suit : <b><font color='#c0392b'>Critique</font></b> = "
        "bloquant pour la production, <b><font color='#d35400'>Haute</font></b> = necessaire pour "
        "la v1 enterprise, <b><font color='#2c7a4a'>Moyenne</font></b> = important mais non bloquant, "
        "<b><font color='#7f8c8d'>Faible</font></b> = amelioration souhaitable, "
        "<b><font color='#1a7a3a'>Valide</font></b> = deja implemente et conforme.",
        body_style
    ))
    story.append(Spacer(1, 12))

    # Sub-sections for each domain
    domains = [
        ("MoA Orchestration", "Le Mixture-of-Agents orchestrateur constitue le coeur du systeme AgentForge. "
         "L'objectif est de supporter 9 modeles LLM en parallele avec un mecanisme de critique croise, "
         "de refinement iteratif et de voting multicritere pondere. Actuellement, seuls 3 a 7 modeles "
         "sont supportes par agent, et le voting est limite a une selection par score combine."),
        ("Reflection Agent", "L'agent de reflection evaluate la qualite des sorties via un LLM reel "
         "(Gemini 2.0 Flash). Les 6 criteres ponderes et le seuil 0.95 sont deja implementes pour le "
         "mode DEV. Le feedback loop vers MoA et la persistance de l'historique restent a implementer."),
        ("RL Router", "Le routeur base sur l'apprentissage par renforcement est actuellement une "
         "heuristique statique sans exploration, sans reward engine, et sans persistance. C'est un "
         "composant critique pour l'optimisation automatique du choix des modeles LLM."),
        ("Cost Optimizer", "L'optimiseur de couts dispose deja d'un scoring qualite/cout/latence "
         "(50/30/20) et d'un EMA sur les 10 dernieres evaluations. Les predictions ML et l'apprentissage "
         "continu restent a developper."),
        ("Auto-Fix Enterprise", "Le systeme de correction automatique n'a que 6 patterns et utilise "
         "du regex-based AST au lieu de ts-morph. La detection des types, imports manquants, references "
         "circulaires et code mort est inexistante ou basique."),
        ("Context Management", "La gestion du contexte est le domaine avec le plus grand ecart. "
         "Aucun des composants (ContextGraph, DependencyResolver, TokenBudgetManager, "
         "ContextCompressionService) n'existe actuellement."),
        ("Sandbox Cloud Native", "Le sandbox actuel utilise Docker avec des cold starts de 2-5s, "
         "sans warm pool, sans scheduler, sans auto-recovery et sans metriques. La cible est une "
         "architecture cloud native avec demarrage <500ms."),
        ("Deploiement Automatise", "Le deploiement est limite aux variables d'environnement. "
         "Aucune integration Cloudflare D1/KV/R2, pas de rollback, ni de preview deployments, "
         "ni de strategie blue/green + canary."),
        ("Observabilite", "L'observabilite se resume a des console.log et un endpoint /health basique. "
         "L'objectif est une stack OpenTelemetry complete avec metrics Prometheus, alertes et dashboard temps reel."),
        ("Admin Control Center", "Le centre d'administration est embryonnaire : CRUD basique pour les "
         "utilisateurs, registre statique pour les agents, pas de gestion providers, pas de dashboard "
         "finance, pas d'audit de securite."),
        ("Securite Enterprise", "La securite repose uniquement sur JWT stateless. Pas de MFA, pas de "
         "device trust, pas de rotation automatique des secrets, pas de dashboard securite, pas d'audit trail."),
        ("Qualite Logicielle", "La couverture de tests est de 0% sur tous les niveaux (unitaires, "
         "integration, E2E, load, chaos). C'est un risque majeur pour la mise en production."),
        ("Multi-Tenant", "L'architecture multi-tenant n'existe pas : base de donnees partagee, "
         "quotas basiques, pas de facturation, pas de branding, RBAC limite a 3 tiers."),
        ("Performance", "Les performances sont limitees : Redis single node, execution directe "
         "sans queue, instance unique sans scaling horizontal, cache non distribue."),
    ]

    for domain_name, domain_desc in domains:
        story.append(Spacer(1, 6))
        story.append(add_heading(domain_name, h3_style, level=1))
        story.append(Paragraph(domain_desc, body_style))
        story.append(Spacer(1, 4))

    story.append(Spacer(1, 12))
    story.append(Paragraph('<b>Tableau complet de conformite</b>', h2_style))
    story.append(Spacer(1, 6))

    conformity_table = build_conformity_table()
    story.append(conformity_table)
    story.append(Spacer(1, 6))
    story.append(Paragraph('Tableau 1 : Matrice de conformite complete - 73 exigences du blueprint AgentForge', caption_style))
    story.append(Spacer(1, 18))

    # ━━━━━━━━━━━━ PHASES 2-13 SUMMARY TABLES ━━━━━━━━━━━━
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    story.append(add_heading('<b>PHASES 2 A 13 - TABLEAUX RECAPITULATIFS</b>', h1_style, level=0))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "Chaque phase de remediation est detaillee ci-dessous avec les composants a implementer, "
        "les fichiers concernes, les descriptions fonctionnelles et l'impact estime sur la plateforme.",
        body_justified
    ))
    story.append(Spacer(1, 12))

    phases = [
        ("PHASE 2", "MoA Orchestration - Montee en puissance", [
            ("MoAOrchestrator", "src/agents/moa/orchestrator.ts", "Orchestration 9 modeles paralleles", "Critique"),
            ("CrossCritiqueEngine", "src/agents/moa/cross-critique.ts", "Critique croise multi-LLM", "Critique"),
            ("RefinementLoop", "src/agents/moa/refinement.ts", "Refinement avec feedback integre", "Haute"),
            ("WeightedVoting", "src/agents/moa/voting.ts", "Voting multicritere pondere", "Haute"),
            ("EarlyExitManager", "src/agents/moa/early-exit.ts", "Optimisation early exit", "Moyenne"),
        ]),
        ("PHASE 3", "Reflection Agent - Boucle de retroaction", [
            ("ReflectionEvaluator", "src/agents/reflection/evaluator.ts", "Evaluation LLM reelle multi-criteres", "Valide"),
            ("FeedbackInjector", "src/agents/reflection/feedback.ts", "Injection feedback dans MoA", "Haute"),
            ("HistoryPersistence", "src/agents/reflection/history.ts", "Persistance historique evolution", "Haute"),
            ("ThresholdManager", "src/agents/reflection/threshold.ts", "Seuils configurables par mode", "Valide"),
        ]),
        ("PHASE 4", "RL Router - Apprentissage par renforcement", [
            ("EpsilonGreedyExplorer", "src/agents/rl/explorer.ts", "Exploration epsilon-greedy avec decay", "Critique"),
            ("RewardEngine", "src/agents/rl/reward.ts", "Reward = f(quality, cost, latency)", "Critique"),
            ("RLDataPersistence", "src/agents/rl/persistence.ts", "Persistance rl_training_data en DB", "Critique"),
            ("UserFeedbackCollector", "src/agents/rl/feedback.ts", "Capture thumbs up/down + rating", "Haute"),
            ("RLDashboard", "src/agents/rl/dashboard.ts", "Metriques temps reel RL", "Haute"),
        ]),
        ("PHASE 5", "Cost Optimizer - Optimisation des couts", [
            ("CostScorer", "src/optimizers/cost/scorer.ts", "Scoring configurable qualite/cout/latence", "Valide"),
            ("EMAHistoryManager", "src/optimizers/cost/ema.ts", "Persistance + EMA glissant", "Haute"),
            ("CostPredictor", "src/optimizers/cost/predictor.ts", "Predictions ML-based", "Moyenne"),
            ("AutoAdjustWeights", "src/optimizers/cost/adjust.ts", "Apprentissage continu auto-adjust", "Haute"),
            ("BudgetAlertSystem", "src/optimizers/cost/alerts.ts", "Alertes budget depasse", "Valide"),
        ]),
        ("PHASE 6", "Auto-Fix Enterprise - Correction intelligente", [
            ("PatternLibrary", "src/autofix/patterns/library.ts", "Bibliotheque 200+ patterns", "Critique"),
            ("TSMorphEngine", "src/autofix/ast/ts-morph.ts", "Vraie AST via ts-morph", "Critique"),
            ("TypeIncompatDetector", "src/autofix/detectors/types.ts", "Detection incompatibilites types", "Haute"),
            ("ImportResolver", "src/autofix/detectors/imports.ts", "Resolution complete des imports", "Haute"),
            ("CircularRefDetector", "src/autofix/detectors/circular.ts", "Analyse graphe dependances", "Moyenne"),
            ("DeadCodeDetector", "src/autofix/detectors/dead-code.ts", "Detection code mort par AST", "Moyenne"),
            ("MultiPassRepair", "src/autofix/repair/multi-pass.ts", "Reparation multi-pass LLM", "Haute"),
        ]),
        ("PHASE 7", "Context Management - Gestion du contexte", [
            ("ContextGraph", "src/context/graph.ts", "Graphe de dependances complet", "Critique"),
            ("DependencyResolver", "src/context/resolver.ts", "Resolution dependances directes", "Critique"),
            ("TokenBudgetManager", "src/context/token-budget.ts", "Limites tokens par fichier", "Critique"),
            ("CompressionService", "src/context/compression.ts", "Compression intelligente", "Haute"),
            ("AutoSummarizer", "src/context/summarizer.ts", "Resume automatique contextes larges", "Haute"),
        ]),
        ("PHASE 8", "Sandbox Cloud Native - Infrastructure", [
            ("WarmPoolManager", "src/sandbox/warm-pool.ts", "Gestionnaire conteneurs pre-chauffes", "Critique"),
            ("SandboxScheduler", "src/sandbox/scheduler.ts", "File de priorite + ordonnancement", "Haute"),
            ("AutoRecoveryEngine", "src/sandbox/recovery.ts", "Redemarrage automatique sur echec", "Haute"),
            ("SandboxMetrics", "src/sandbox/metrics.ts", "Suivi CPU/memoire/latence", "Haute"),
            ("ContainerOrchestrator", "src/sandbox/orchestrator.ts", "Orchestration conteneurs <500ms", "Critique"),
        ]),
        ("PHASE 9", "Deploiement Automatise - CI/CD Enterprise", [
            ("CloudflareDeployer", "src/deploy/cloudflare/engine.ts", "Moteur deploiement Cloudflare", "Critique"),
            ("D1KV2Manager", "src/deploy/cloudflare/bindings.ts", "Gestion D1/KV/R2 bindings", "Haute"),
            ("RollbackManager", "src/deploy/rollback.ts", "Rollback automatique sur echec", "Haute"),
            ("PreviewDeployer", "src/deploy/preview.ts", "Deploiements preview par branche", "Moyenne"),
            ("ProgressiveRollout", "src/deploy/rollout.ts", "Strategie blue/green + canary", "Haute"),
        ]),
        ("PHASE 10", "Observabilite - Monitoring complet", [
            ("OTELTracer", "src/observability/tracing.ts", "Tracing distribue OpenTelemetry", "Critique"),
            ("MetricsService", "src/observability/metrics.ts", "Metriques Prometheus-compatible", "Haute"),
            ("AlertManager", "src/observability/alerts.ts", "Alertes basees sur seuils", "Haute"),
            ("RealtimeDashboard", "src/observability/dashboard.ts", "Dashboard monitoring temps reel", "Haute"),
        ]),
        ("PHASE 11", "Admin + Securite - Gouvernance", [
            ("UserAdminCRUD", "src/admin/users/crud.ts", "CRUD complet + quotas utilisateurs", "Haute"),
            ("AgentConfigManager", "src/admin/agents/config.ts", "Configuration dynamique agents", "Haute"),
            ("ProviderMonitor", "src/admin/providers/monitor.ts", "Suivi cout/qualite/latence providers", "Haute"),
            ("MFATOTPService", "src/security/mfa/totp.ts", "MFA base sur TOTP", "Critique"),
            ("DeviceTrustEngine", "src/security/device/trust.ts", "Fingerprinting appareils", "Haute"),
            ("SessionManager", "src/security/session/manager.ts", "Sessions cote serveur", "Haute"),
            ("SecretRotator", "src/security/secrets/rotator.ts", "Rotation automatique secrets", "Haute"),
            ("AuditTrailLogger", "src/security/audit/logger.ts", "Journalisation complete actions", "Haute"),
        ]),
        ("PHASE 12", "Qualite + Multi-Tenant - Industrialisation", [
            ("TestFramework", "tests/framework/setup.ts", "Framework tests unitaires >80%", "Critique"),
            ("IntegrationTestSuite", "tests/integration/suite.ts", "Tests integration API + services", "Critique"),
            ("E2ETestRunner", "tests/e2e/runner.ts", "Tests E2E flux critiques", "Haute"),
            ("TenantIsolationLayer", "src/tenant/isolation.ts", "Isolation schema-per-tenant", "Critique"),
            ("QuotaManager", "src/tenant/quotas.ts", "Quotas fine-grained par tenant", "Haute"),
            ("BillingIntegration", "src/tenant/billing/stripe.ts", "Integration Stripe/billing", "Haute"),
            ("RBACEngine", "src/tenant/rbac/engine.ts", "RBAC avance multi-niveaux", "Haute"),
        ]),
        ("PHASE 13", "Performance - Passage a l'echelle", [
            ("RedisClusterManager", "src/performance/redis-cluster.ts", "Redis Cluster pour HA", "Haute"),
            ("JobQueueProcessor", "src/performance/job-queue.ts", "BullMQ/job queue asynchrone", "Critique"),
            ("HorizontalScaler", "src/performance/scaler.ts", "Scaling horizontal stateless + LB", "Haute"),
            ("DistributedCache", "src/performance/distributed-cache.ts", "Couche cache distribuee", "Haute"),
        ]),
    ]

    for phase_num, phase_title, rows in phases:
        story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
        story.append(add_heading('<b>%s - %s</b>' % (phase_num, phase_title), h2_style, level=1))
        story.append(Spacer(1, 6))
        phase_table = build_phase_table(phase_num, phase_title, rows)
        story.append(phase_table)
        story.append(Spacer(1, 6))
        phase_idx = phases.index((phase_num, phase_title, rows)) + 2
        story.append(Paragraph('Tableau %d : Composants de la %s' % (phase_idx, phase_title.lower()), caption_style))
        story.append(Spacer(1, 12))

    # ━━━━━━━━━━━━ ARCHITECTURE CIBLE ━━━━━━━━━━━━
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    story.append(add_heading('<b>ARCHITECTURE CIBLE</b>', h1_style, level=0))
    story.append(Spacer(1, 8))

    story.append(add_heading('Vision globale', h2_style, level=1))
    story.append(Paragraph(
        "L'architecture cible d'AgentForge est une plateforme cloud native enterprise, concue pour "
        "le passage a l'echelle, la haute disponibilite et l'observabilite complete. Elle repose sur "
        "les principes suivants :",
        body_justified
    ))
    story.append(Spacer(1, 6))

    principles = [
        "<b>Architecture orientee agents</b> : Chaque composant (MoA, Reflection, RL Router, Auto-Fix) "
        "est un agent autonome avec sa propre boucle de decision et ses metriques.",
        "<b>Observabilite native</b> : OpenTelemetry integre des la conception, avec tracing distribue, "
        "metrics Prometheus et alertes automatiques.",
        "<b>Multi-tenant par conception</b> : Isolation des donnees au niveau schema, quotas fine-grained, "
        "facturation integree et RBAC multi-niveaux.",
        "<b>Deploiement progressif</b> : Strategie blue/green + canary pour les mises en production, "
        "avec rollback automatique sur detection d'anomalie.",
        "<b>Optimisation continue</b> : RL Router pour le choix optimal des modeles LLM, Cost Optimizer "
        "avec predictions ML et auto-adjustement des poids.",
        "<b>Securite Zero Trust</b> : MFA TOTP, device trust, sessions serveur, rotation automatique "
        "des secrets et audit trail complet.",
    ]
    for p in principles:
        story.append(Paragraph(p, bullet_style, bulletText='\u2022'))
    story.append(Spacer(1, 12))

    story.append(add_heading('Diagramme des composants', h2_style, level=1))
    story.append(Paragraph(
        "L'architecture cible s'organise en 6 couches horizontales :",
        body_justified
    ))
    story.append(Spacer(1, 6))

    layers = [
        "<b>Couche Presentation</b> : Admin Control Center, Dashboard monitoring, Orchestration UI",
        "<b>Couche API Gateway</b> : Rate limiting, Auth/MFA, RBAC, Routing multi-tenant",
        "<b>Couche Orchestration</b> : MoA Orchestrator, Reflection Agent, RL Router, Cost Optimizer",
        "<b>Couche Execution</b> : Auto-Fix Engine, Context Management, Sandbox Cloud Native, Job Queue",
        "<b>Couche Infrastructure</b> : Redis Cluster, Distributed Cache, Warm Pool, Metrics/Prometheus",
        "<b>Couche Deploiement</b> : Cloudflare Workers/Pages, D1/KV/R2, CI/CD Pipeline, Blue/Green",
    ]
    for l in layers:
        story.append(Paragraph(l, bullet_style, bulletText='\u2022'))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Chaque couche communique exclusivement via des interfaces definies, avec un tracing "
        "distribue OTEL couvrant l'integralite du chemin de la requete.",
        body_justified
    ))
    story.append(Spacer(1, 18))

    # ━━━━━━━━━━━━ PLAN DE MIGRATION ━━━━━━━━━━━━
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    story.append(add_heading('<b>PLAN DE MIGRATION</b>', h1_style, level=0))
    story.append(Spacer(1, 8))

    story.append(add_heading('Etapes de migration par priorite', h2_style, level=1))
    story.append(Paragraph(
        "Le plan de migration suit une approche incrementale, en privilegiant les composants critiques "
        "et en minimisant les risques de regression. L'ordre des phases respecte les dependances "
        "techniques entre composants.",
        body_justified
    ))
    story.append(Spacer(1, 6))

    migration_steps = [
        "<b>Etape 1 - Fondations (Semaines 1-4)</b> : Mise en place du framework de tests unitaires, "
        "implementation du tracing OTEL et du Job Queue. Ces composants sont les prerequis pour toutes "
        "les phases suivantes.",
        "<b>Etape 2 - Coeur agentique (Semaines 5-10)</b> : Montee en puissance du MoA (9 modeles), "
        "implementation du RL Router avec exploration epsilon-greedy et Reward Engine. Boucle de "
        "feedback Reflection vers MoA.",
        "<b>Etape 3 - Intelligence (Semaines 11-16)</b> : Auto-Fix Enterprise avec ts-morph et 200+ "
        "patterns. Context Management complet (ContextGraph, TokenBudget, Compression). Cost Optimizer "
        "avec predictions ML.",
        "<b>Etape 4 - Infrastructure (Semaines 17-22)</b> : Sandbox Cloud Native avec Warm Pool, "
        "Scheduler et Auto-Recovery. Redis Cluster et Distributed Cache.",
        "<b>Etape 5 - Deploiement (Semaines 23-26)</b> : Pipeline CI/CD complet avec Cloudflare, "
        "Rollback, Preview et Blue/Green. Integration D1/KV/R2.",
        "<b>Etape 6 - Gouvernance (Semaines 27-32)</b> : Securite Enterprise (MFA, Device Trust, "
        "Audit). Admin Control Center complet. Multi-Tenant avec isolation et facturation.",
        "<b>Etape 7 - Industrialisation (Semaines 33-36)</b> : Tests E2E et integration complets, "
        "Load Testing, Chaos Testing. Horizontal Scaling et optimisations performance.",
    ]
    for step in migration_steps:
        story.append(Paragraph(step, bullet_style, bulletText='\u2022'))
    story.append(Spacer(1, 18))

    story.append(add_heading('Evaluation des risques', h2_style, level=1))
    story.append(Spacer(1, 6))
    risk_table = build_risk_table()
    story.append(risk_table)
    story.append(Spacer(1, 6))
    story.append(Paragraph('Tableau : Evaluation des risques du plan de migration', caption_style))
    story.append(Spacer(1, 18))

    # ━━━━━━━━━━━━ FILES TO MODIFY / CREATE ━━━━━━━━━━━━
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    story.append(add_heading('<b>FICHIERS A MODIFIER / CREER</b>', h1_style, level=0))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "L'inventaire complet des fichiers a creer ou modifier, organises par phase de remediation. "
        "Les fichiers modifies (Update) existent dans la plateforme MVP actuelle et necessitent des "
        "evolutions significatives. Les fichiers crees (Create) sont de nouveaux composants.",
        body_justified
    ))
    story.append(Spacer(1, 8))

    file_lists = [
        ("Phase 2 - MoA Orchestration", [
            ("src/agents/moa/orchestrator.ts", "Update", "2", "Montee de 3-7 a 9 modeles paralleles"),
            ("src/agents/moa/cross-critique.ts", "Create", "2", "Moteur de critique croise multi-LLM"),
            ("src/agents/moa/refinement.ts", "Update", "2", "Refinement avec feedback integre"),
            ("src/agents/moa/voting.ts", "Update", "2", "Voting multicritere pondere"),
            ("src/agents/moa/early-exit.ts", "Update", "2", "Optimisation early exit"),
            ("src/agents/moa/types.ts", "Create", "2", "Types et interfaces MoA"),
        ]),
        ("Phase 3 - Reflection Agent", [
            ("src/agents/reflection/evaluator.ts", "Update", "3", "Evaluation multi-criteres"),
            ("src/agents/reflection/feedback.ts", "Create", "3", "Injection feedback dans MoA"),
            ("src/agents/reflection/history.ts", "Create", "3", "Persistance historique"),
            ("src/agents/reflection/threshold.ts", "Update", "3", "Seuils configurables"),
        ]),
        ("Phase 4 - RL Router", [
            ("src/agents/rl/explorer.ts", "Create", "4", "Exploration epsilon-greedy"),
            ("src/agents/rl/reward.ts", "Create", "4", "Reward engine multi-facteurs"),
            ("src/agents/rl/persistence.ts", "Create", "4", "Persistance donnees entrainement"),
            ("src/agents/rl/feedback.ts", "Create", "4", "Collecte feedback utilisateur"),
            ("src/agents/rl/dashboard.ts", "Create", "4", "Dashboard metriques RL"),
        ]),
        ("Phase 5 - Cost Optimizer", [
            ("src/optimizers/cost/scorer.ts", "Update", "5", "Scoring configurable"),
            ("src/optimizers/cost/ema.ts", "Update", "5", "EMA glissant + persistance"),
            ("src/optimizers/cost/predictor.ts", "Create", "5", "Predictions ML-based"),
            ("src/optimizers/cost/adjust.ts", "Create", "5", "Auto-adjust weights"),
            ("src/optimizers/cost/alerts.ts", "Create", "5", "Systeme d'alertes budget"),
        ]),
        ("Phase 6 - Auto-Fix Enterprise", [
            ("src/autofix/patterns/library.ts", "Create", "6", "Bibliotheque 200+ patterns"),
            ("src/autofix/ast/ts-morph.ts", "Create", "6", "Moteur AST ts-morph"),
            ("src/autofix/detectors/types.ts", "Create", "6", "Detection types"),
            ("src/autofix/detectors/imports.ts", "Create", "6", "Resolution imports"),
            ("src/autofix/detectors/circular.ts", "Create", "6", "References circulaires"),
            ("src/autofix/detectors/dead-code.ts", "Create", "6", "Code mort"),
            ("src/autofix/repair/multi-pass.ts", "Create", "6", "Reparation multi-pass"),
        ]),
        ("Phase 7 - Context Management", [
            ("src/context/graph.ts", "Create", "7", "Graphe de dependances"),
            ("src/context/resolver.ts", "Create", "7", "Resolution dependances"),
            ("src/context/token-budget.ts", "Create", "7", "Budget tokens par fichier"),
            ("src/context/compression.ts", "Create", "7", "Compression intelligente"),
            ("src/context/summarizer.ts", "Create", "7", "Resume automatique"),
        ]),
        ("Phase 8 - Sandbox Cloud Native", [
            ("src/sandbox/warm-pool.ts", "Create", "8", "Warm Pool Manager"),
            ("src/sandbox/scheduler.ts", "Create", "8", "Ordonnancement"),
            ("src/sandbox/recovery.ts", "Create", "8", "Auto-recovery"),
            ("src/sandbox/metrics.ts", "Create", "8", "Metriques sandbox"),
            ("src/sandbox/orchestrator.ts", "Create", "8", "Orchestration conteneurs"),
        ]),
        ("Phase 9 - Deploiement Automatise", [
            ("src/deploy/cloudflare/engine.ts", "Create", "9", "Moteur deploiement"),
            ("src/deploy/cloudflare/bindings.ts", "Create", "9", "Bindings D1/KV/R2"),
            ("src/deploy/rollback.ts", "Create", "9", "Rollback automatique"),
            ("src/deploy/preview.ts", "Create", "9", "Preview deployments"),
            ("src/deploy/rollout.ts", "Create", "9", "Blue/green + canary"),
        ]),
        ("Phase 10 - Observabilite", [
            ("src/observability/tracing.ts", "Create", "10", "Tracing OTEL"),
            ("src/observability/metrics.ts", "Create", "10", "Metrics Prometheus"),
            ("src/observability/alerts.ts", "Create", "10", "Alertes seuils"),
            ("src/observability/dashboard.ts", "Create", "10", "Dashboard temps reel"),
        ]),
        ("Phase 11 - Admin + Securite", [
            ("src/admin/users/crud.ts", "Update", "11", "CRUD complet utilisateurs"),
            ("src/admin/agents/config.ts", "Create", "11", "Config dynamique agents"),
            ("src/admin/providers/monitor.ts", "Create", "11", "Suivi providers"),
            ("src/security/mfa/totp.ts", "Create", "11", "MFA TOTP"),
            ("src/security/device/trust.ts", "Create", "11", "Device fingerprinting"),
            ("src/security/session/manager.ts", "Create", "11", "Sessions serveur"),
            ("src/security/secrets/rotator.ts", "Create", "11", "Rotation secrets"),
            ("src/security/audit/logger.ts", "Create", "11", "Audit trail"),
        ]),
        ("Phase 12 - Qualite + Multi-Tenant", [
            ("tests/framework/setup.ts", "Create", "12", "Framework tests"),
            ("tests/integration/suite.ts", "Create", "12", "Tests integration"),
            ("tests/e2e/runner.ts", "Create", "12", "Tests E2E"),
            ("src/tenant/isolation.ts", "Create", "12", "Isolation tenant"),
            ("src/tenant/quotas.ts", "Create", "12", "Quotas fine-grained"),
            ("src/tenant/billing/stripe.ts", "Create", "12", "Integration Stripe"),
            ("src/tenant/rbac/engine.ts", "Create", "12", "RBAC avance"),
        ]),
        ("Phase 13 - Performance", [
            ("src/performance/redis-cluster.ts", "Create", "13", "Redis Cluster"),
            ("src/performance/job-queue.ts", "Create", "13", "BullMQ job queue"),
            ("src/performance/scaler.ts", "Create", "13", "Horizontal scaling"),
            ("src/performance/distributed-cache.ts", "Create", "13", "Cache distribue"),
        ]),
    ]

    for section_title, files in file_lists:
        story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
        story.append(add_heading(section_title, h3_style, level=1))
        story.append(Spacer(1, 4))
        ft = build_file_list_table(files, section_title)
        story.append(ft)
        story.append(Spacer(1, 8))

    # ━━━━━━━━━━━━ CONFORMITY SCORE ━━━━━━━━━━━━
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    story.append(add_heading('<b>SCORE DE CONFORMITE</b>', h1_style, level=0))
    story.append(Spacer(1, 8))

    story.append(add_heading('Calcul du score actuel', h2_style, level=1))
    story.append(Paragraph(
        "Le score de conformite est calcule en ponderant chaque domaine selon son importance relative "
        "dans le blueprint. Les domaines critiques (MoA, RL Router, Context Management, Securite) "
        "ont un poids superieur aux domaines d'amelioration continue (Qualite, Performance).",
        body_justified
    ))
    story.append(Spacer(1, 8))

    score_table = build_conformity_score_table()
    story.append(score_table)
    story.append(Spacer(1, 6))
    story.append(Paragraph('Tableau : Score de conformite par domaine - Actuel vs Cible', caption_style))
    story.append(Spacer(1, 12))

    story.append(add_heading('Analyse du score', h2_style, level=1))
    story.append(Paragraph(
        "Le score global de conformite actuel est estime a <b>13%</b>, ce qui signifie que la "
        "plateforme MVP ne couvre que 13% des exigences du blueprint enterprise. Les domaines "
        "les plus en retrait sont Context Management (0%), Qualite Logicielle (0%), Sandbox (0%), "
        "Multi-Tenant (3%) et Securite Enterprise (2%).",
        body_justified
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Apres implementation complete du programme de remediation (Phases 2 a 13), le score cible "
        "est de <b>100%</b> sur tous les domaines. Les gains les plus significatifs seront obtenus "
        "lors des Phases 2 (MoA), 4 (RL Router), 6 (Auto-Fix) et 7 (Context Management), qui "
        "representent a elles seules plus de 60% de l'ecart total.",
        body_justified
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Le ROI est maximise en privilegiant les phases a fort impact et forte urgence : la Phase 7 "
        "(Context Management) comblera le plus grand ecart (100%), suivie de la Phase 8 (Sandbox) "
        "et de la Phase 12 (Qualite + Multi-Tenant).",
        body_justified
    ))
    story.append(Spacer(1, 18))

    # ━━━━━━━━━━━━ CONCLUSION ━━━━━━━━━━━━
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    story.append(add_heading('<b>CONCLUSION</b>', h1_style, level=0))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "Ce programme de remediation strategique definit la feuille de route complete pour transformer "
        "AgentForge d'une plateforme MVP fonctionnelle en une architecture enterprise cloud native. "
        "Avec 73 exigences analysees, 13 phases de remediation et un score de conformite actuel de 13%, "
        "le chemin vers la conformite est ambitieux mais structure.",
        body_justified
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Les points cles a retenir :",
        body_style
    ))
    story.append(Spacer(1, 4))

    conclusions = [
        "<b>7 exigences validees</b> sur 73 (10%) - principalement dans MoA et Reflection Agent",
        "<b>31 exigences critiques</b> necessitent une implementation immediate ou a court terme",
        "<b>5 domaines a 0%</b> de conformite (Context Management, Sandbox, Qualite, Multi-Tenant, Securite)",
        "<b>36 semaines estimees</b> pour l'implementation complete du programme",
        "<b>8 risques identifies</b> avec des strategies de mitigation definies pour chacun",
        "<b>67 fichiers a creer</b> et <b>6 fichiers a modifier</b> significativement",
    ]
    for c in conclusions:
        story.append(Paragraph(c, bullet_style, bulletText='\u2022'))

    story.append(Spacer(1, 12))
    story.append(Paragraph(
        "La reussite de ce programme repose sur une execution disciplinee, un testing rigoureux a "
        "chaque phase, et une surveillance continue des metriques de conformite. Le RL Router et "
        "l'observabilite OTEL doivent etre implementes en priorite car ils fournissent les boucles "
        "de retroaction necessaires a l'optimisation continue de la plateforme.",
        body_justified
    ))

    # ━━ Build ━━
    doc.multiBuild(story)
    print(f"Body PDF generated: {output_path}")


if __name__ == '__main__':
    build_document()
